/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rdice;

import java.util.Random;
import javax.swing.JTextField;

public class diceRoll extends javax.swing.JFrame {

    public diceRoll() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        tfSum1 = new javax.swing.JTextField();
        tfDice1 = new javax.swing.JTextField();
        tfDice2 = new javax.swing.JTextField();
        btnRoll = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        tfDice3 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        tfDice4 = new javax.swing.JTextField();
        lbl6 = new javax.swing.JLabel();
        tfSum2 = new javax.swing.JTextField();
        lbl7 = new javax.swing.JLabel();
        tfSum3 = new javax.swing.JTextField();
        tfMatrix = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("=");

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("First throw:");

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("+");

        tfSum1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfSum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSum1ActionPerformed(evt);
            }
        });

        tfDice1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfDice1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDice1ActionPerformed(evt);
            }
        });

        tfDice2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfDice2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDice2ActionPerformed(evt);
            }
        });

        btnRoll.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRoll.setText("Roll!");
        btnRoll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRollMouseReleased(evt);
            }
        });
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        lbl4.setBackground(new java.awt.Color(255, 255, 255));
        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Final:");

        tfDice3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfDice3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDice3ActionPerformed(evt);
            }
        });

        lbl5.setBackground(new java.awt.Color(255, 255, 255));
        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("+");

        tfDice4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfDice4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDice4ActionPerformed(evt);
            }
        });

        lbl6.setBackground(new java.awt.Color(255, 255, 255));
        lbl6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setText("=");

        tfSum2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfSum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSum2ActionPerformed(evt);
            }
        });

        lbl7.setBackground(new java.awt.Color(255, 255, 255));
        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("Second throw:");

        tfSum3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfSum3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSum3ActionPerformed(evt);
            }
        });

        tfMatrix.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfMatrix.setForeground(new java.awt.Color(102, 255, 51));
        tfMatrix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatrixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(189, 189, 189))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRoll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSum3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfDice3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfDice4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfSum2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lbl3)
                                        .addGap(118, 118, 118)
                                        .addComponent(lbl2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfSum1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(tfDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(331, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(tfDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(lbl7)
                    .addContainerGap(217, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lbl1)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl3)
                            .addComponent(lbl2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tfMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSum1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lbl5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfDice4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSum2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbl6)
                                    .addGap(36, 36, 36)))
                            .addComponent(tfDice3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59)
                .addComponent(lbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSum3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnRoll)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(tfDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(578, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(tfDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(578, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(264, 264, 264)
                    .addComponent(lbl7)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSum1ActionPerformed

    private void tfDice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDice1ActionPerformed

    private void tfDice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDice2ActionPerformed

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed
        // first throw
        Random rn = new Random();
        int min = 1;
        int max = 6;
        
        int randNum1 = (int)(Math.random() * (max - min + 1)) + min;
        int randNum2 = (int)(Math.random() * (max - min + 1)) + min;
        
        tfDice1.setText(String.valueOf(randNum1));
        tfDice2.setText(String.valueOf(randNum2));

        int dice1Value = Integer.parseInt(tfDice1.getText());
        int dice2Value = Integer.parseInt(tfDice2.getText());

        tfSum1.setText(String.valueOf(dice1Value + dice2Value));
                
        //second throw
        int randNum3 = (int)(Math.random() * (max - min + 1)) + min;
        int randNum4 = (int)(Math.random() * (max - min + 1)) + min;
        
        tfDice3.setText(String.valueOf(randNum3));
        tfDice4.setText(String.valueOf(randNum4));

        int dice3Value = Integer.parseInt(tfDice3.getText());
        int dice4Value = Integer.parseInt(tfDice4.getText());

        tfSum2.setText(String.valueOf(dice3Value + dice4Value));
        
        //Final 
        tfSum3.setText(String.valueOf(dice1Value + dice2Value+dice3Value + dice4Value));
        
        //matrix rotation based on first throw       
        String position = "1234";
        int rotations =  dice1Value + dice2Value + 2;
        int length = position.length();
        rotations = rotations % length;
        String rotatedString = position.substring(length - rotations) + position.substring(0, length - rotations);
        
        char direction = rotatedString.charAt(0);
        switch (direction) {
            case '1' -> tfMatrix.setText("▼");
            case '2' -> tfMatrix.setText("◄");
            case '3' -> tfMatrix.setText("▲");
            case '4' -> tfMatrix.setText("►");
            default -> tfMatrix.setText("Invalid direction");
        }
        

            
  
  
    }//GEN-LAST:event_btnRollActionPerformed

    private void btnRollMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRollMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRollMouseReleased

    private void tfDice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDice3ActionPerformed

    private void tfDice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDice4ActionPerformed

    private void tfSum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSum2ActionPerformed

    private void tfSum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSum3ActionPerformed

    private void tfMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diceRoll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRoll;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JTextField tfDice1;
    private javax.swing.JTextField tfDice2;
    private javax.swing.JTextField tfDice3;
    private javax.swing.JTextField tfDice4;
    private javax.swing.JTextField tfMatrix;
    private javax.swing.JTextField tfSum1;
    private javax.swing.JTextField tfSum2;
    private javax.swing.JTextField tfSum3;
    // End of variables declaration//GEN-END:variables

    private String rotateString(String number, JTextField rotation) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String rotateString(String pos, int rots) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
